### ISSUE TITLE
Negative sampling size?

### ISSUE THREAD

**Issue by gokcemuge** [stasl0217/UKGE#10]
What are the negative sampling sizes for the best hyper-parameter combinations given in the paper?

Also parameter n_neg is explained as "Number of negative samples per (h,r,t)" in the code, in run.py. 
However, in the implementation both head and tail are corrupted separately for each triple which results in double size of n_neg negative samples per (h,r,t).

**Comment by stasl0217** [comment]
Negative sample size is 10
