### ISSUE TITLE
Some problems in data

### ISSUE THREAD

**Issue by YaooXu** [stasl0217/UKGE#11]
2000+ triples appear in both train.tsv and test.tsv with different confidence.

e.g.
![image](https://user-images.githubusercontent.com/44971199/124720977-480fed80-df3b-11eb-9bac-f427ae3b3d9a.png)

**Comment by stasl0217** [comment]
Hi, This is due to a relabeling problem in original ConceptNet 5. The new test_with_neg.tsv should have resolved this problem.

**Comment by YaooXu** [comment]
But it seems to affect the results of nDCG prediction. As you use test.tsv for nDCG prediction.
