### ISSUE TITLE
python run.py error 

### ISSUE THREAD

**Issue by David-Lee-1990** [stasl0217/UKGE#2]
Thank you for sharing your code and data.  When I run 'python run.py', it gives me 'No train.csv' error. Google drive link that provided in Readme does not have those data. Where can i get those data? Thank you

**Comment by stasl0217** [comment]
Hi David! Files like 'train.csv' can be obtained by splitting the data.tsv in the zipped file on Google drive. I have uploaded the intermediate files that we used in experiments. No available entity or relation labels for some of the intermediate files, though.

**Comment by David-Lee-1990** [comment]
ok, thank you
