### ISSUE TITLE
About negative sampling in training process

### ISSUE THREAD

**Issue by yhshu** [stasl0217/UKGE#5]
In the following function, UKGE has an implementation about corrupt a batch for training:
https://github.com/stasl0217/UKGE/blob/7f62d21b8f390694874641c7efac821292a5ba05/src/data.py#L295

```
    def corrupt_batch(self, h_batch, r_batch, t_batch):
        N = self.this_data.num_cons()  # number of entities

        neg_hn_batch = np.random.randint(0, N, size=(
        self.batch_size, self.neg_per_positive))  # random index without filtering
        neg_rel_hn_batch = np.tile(r_batch, (self.neg_per_positive, 1)).transpose()  # copy
        neg_t_batch = np.tile(t_batch, (self.neg_per_positive, 1)).transpose()

        neg_h_batch = np.tile(h_batch, (self.neg_per_positive, 1)).transpose()
        neg_rel_tn_batch = neg_rel_hn_batch
        neg_tn_batch = np.random.randint(0, N, size=(self.batch_size, self.neg_per_positive))

        return neg_hn_batch, neg_rel_hn_batch, neg_t_batch, neg_h_batch, neg_rel_tn_batch, neg_tn_batch
```

However, is it possible to sample positive samples in such a random sampling method, which causes the model to fail to learn?

**Comment by yhshu** [comment]
During the test, negative sampling has another implementation, in which triples that have appeared will not be used as negative samples.

**Comment by stasl0217** [comment]
We experimented with both implementation. The former implementation did not hurt the performance much but greatly sped up training.
