### ISSUE TITLE
psl batch size

### ISSUE THREAD

**Issue by gokcemuge** [stasl0217/UKGE#8]
Hi!

https://github.com/stasl0217/UKGE/blob/7f62d21b8f390694874641c7efac821292a5ba05/src/trainer.py#L227

in every epoch of training, for each batch, a psl batch with random triple(s) is generated and its default size is 1.  What should be the exact psl batch size for the experiments in the paper? And why is it randomly generated?

**Comment by stasl0217** [comment]
Hi, the psl samples are loaded from the preprocessed file softlogic.tsv. It is not randomly generated.
