### ISSUE TITLE
Test sets missing

### ISSUE THREAD

**Issue by gmgm12** [stasl0217/UKGE#9]
In the paper, it is mentioned as:
" To test if our model can correctly interpret negative links, we add the same amount of negative links as existing relation facts into the test sets." 
Where are these test sets or would you share how you produce them?
I couldn't reproduce any of your results unfortunately.

**Comment by stasl0217** [comment]
Hi, Thanks for bringing this to my attention. The test_with_neg.tsv has been uploaded
